# Generated by Django 4.1.4 on 2023-02-28 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_comuna', models.CharField(max_length=6)),
                ('nom_comuna', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='estadocivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_estadocivil', models.CharField(max_length=2)),
                ('estadocivil', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_pais', models.CharField(max_length=5)),
                ('nom_pais', models.TextField(max_length=100)),
                ('abre_pais', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='prevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_prevision', models.CharField(max_length=2)),
                ('prevision_nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_provincia', models.CharField(max_length=5)),
                ('nom_provincia', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_region', models.CharField(max_length=5)),
                ('nom_region', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_sexo', models.CharField(max_length=2)),
                ('letra_sexo', models.CharField(max_length=2)),
                ('nom_sexo', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Basecliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id2cliente', models.IntegerField(blank=True, null=True, verbose_name='numero de presupuesto')),
                ('rut', models.CharField(blank=True, max_length=11, null=True, verbose_name='RUT')),
                ('nombre', models.TextField(blank=True, max_length=200, null=True, verbose_name='Nombres')),
                ('appaterno', models.TextField(blank=True, max_length=100, null=True, verbose_name='Apellido Paterno')),
                ('apmaterno', models.TextField(blank=True, max_length=100, null=True, verbose_name='Apellido Materno')),
                ('fechanacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('direccion', models.TextField(blank=True, max_length=200, null=True)),
                ('ciudad', models.TextField(blank=True, max_length=150, null=True, verbose_name='Ciudad')),
                ('fonomovil', models.TextField(blank=True, max_length=20, null=True, verbose_name='celular')),
                ('fonofijo', models.TextField(blank=True, max_length=20, null=True, verbose_name='Telefono Fijo')),
                ('email', models.TextField(blank=True, max_length=30, null=True)),
                ('ppn', models.IntegerField(blank=True, null=True)),
                ('Nacionalidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='cliente.pais')),
                ('comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='cliente.comuna')),
                ('estadocivil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='cliente.estadocivil', verbose_name='Estado Civil')),
                ('prevision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='cliente.prevision')),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='cliente.provincia')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='cliente.region')),
                ('sexo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='cliente.sexo')),
            ],
        ),
    ]
