# Generated by Django 4.1.4 on 2023-02-28 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProcedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_proced', models.CharField(max_length=30, verbose_name='tipo de procedimientos')),
            ],
        ),
        migrations.CreateModel(
            name='presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_presup', models.IntegerField(verbose_name='Num de presupuesto')),
                ('sub_presu', models.IntegerField(default=1, verbose_name='sub presupuesto')),
                ('fecha_presu', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creacion')),
                ('fecha_modif_presu', models.DateTimeField(auto_now=True, verbose_name='ultima modificación')),
                ('fecha_hospi', models.DateField(blank=True, null=True, verbose_name='Fecha probable de intervención')),
                ('medico_tratante', models.CharField(max_length=200, verbose_name='Medico Tratante')),
                ('especialidad_med', models.CharField(max_length=100)),
                ('Rut_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='cliente.basecliente')),
                ('prevision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='cliente.prevision')),
                ('tipo_proced', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='presupuesto.tipoprocedimiento')),
            ],
        ),
    ]
