# Generated by Django 4.1.4 on 2023-03-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='fl_cot_selec',
            field=models.BooleanField(default=False, verbose_name='cotizacion seleccionada'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='fl_pres_actualizado',
            field=models.BooleanField(default=False, verbose_name='presupuesto modificado'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='fl_presu_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
